### ISSUE TITLE
Merging into Anki?

### ISSUE THREAD

**Issue by dae** [hgiesel/anki_frozen_fields#3]
Hi Henrik,

Partly related to the message I sent you over on the forums - is integrating this functionality into Anki's codebase something you'd be interested in doing?

**Comment by hgiesel** [comment]
I think that could be done. Do you plan to include this for 2.1.41?

Regarding the flake icons, I remember downloading them from a website, which explicitly stated it didn't need any attribution. Reverse searching it just now however did yield both websites like [this one, which does not require attribution](https://pixabay.com/vectors/snowflake-plate-crystal-snow-cold-99326/), or [this one, which wants you to pay for a license](https://stock.adobe.com/102383818?as_campaign=TinEye&as_content=tineye_match&epi1=102383818&tduid=663bbbed3f419d5cbdcb58b10b850b0d&as_channel=affiliate&as_campclass=redirect&as_source=arvato). I have little experience with this, but if you say, it involves too much risk, I can create an icon from scratch.

**Comment by dae** [comment]
A different icon might be better - have dropped you an email.

**Comment by kleinerpirat** [comment]
These flakes are inspired by the ones you're using currently:

![flake_black](https://user-images.githubusercontent.com/62722460/109403356-1e2b3680-795d-11eb-864d-2c8d9e130238.png) ![flake_blue](https://user-images.githubusercontent.com/62722460/109403358-1ec3cd00-795d-11eb-9ca7-21f70ec1406f.png) ![flake_white](https://user-images.githubusercontent.com/62722460/109403359-1ec3cd00-795d-11eb-8d98-c867267098f3.png) <- white

If you like them, feel free to use them Henrik.

### Alternative proposal
I always wondered why the "freezing" metaphor was used for locking fields though. Why not use a lock?

![image](https://user-images.githubusercontent.com/62722460/109423380-6e4add00-79df-11eb-8a35-8fd2d3b1f931.png)

By dropping the need to convey ice, you can use more fitting colors for light and dark theme and it becomes much easier to discern what's locked from what isn't. By using a gray color the inactive state, it looks more tidy and less distracting in my opinion.
<details>
  <summary>The locks:</summary>
  
  ## Inactive
![lock_gray](https://user-images.githubusercontent.com/62722460/109423508-f8934100-79df-11eb-9c05-4e052f8a2461.png)
  ## Light theme
![lock_blue](https://user-images.githubusercontent.com/62722460/109423514-fe892200-79df-11eb-8574-db93dcc76f51.png)
  ## Dark theme
![lock_orange](https://user-images.githubusercontent.com/62722460/109423516-0052e580-79e0-11eb-8975-9ceced505324.png)
</details>

My personal motivation to convince you of the locks is my partial color-blindness. With the current Ze Frozen Fields, it is really hard for me to discern activated fields. It's just too busy. Since a lot of people besides me suffer from some sort of color-blindness, I believe this would be very helpful.

_I designed every icon here (snowflakes and locks). You have my permission to use them._

**Comment by hgiesel** [comment]
@kleinerpirat 
I think the "snow flake" symbolic is just historical. I adoped it from Glutanimate's add-on, whereas he adopted it from [Tiago Barrosos add-on](https://github.com/tmbb/FrozenFields), which was made all the way back in 2012.

But it's funny that you mentioned it, because Damien also suggested a different icon, but he suggested a [pin / thumbtack](https://icons.getbootstrap.com/icons/pin-angle-fill/). But now looking at the lock icons, I also think they might be an even better fit, and it's great that you don't even need to adjust colors to differentiate states.

At the time of writing the PR, I [already opened the PR](https://github.com/ankitects/anki/pull/1046), but I will integrate your suggestion.
